### ISSUE TITLE
Multiple widgets invalid due to duplicate ID

### ISSUE THREAD

**Issue by jaden** [satrya/advanced-random-posts-widget#2]
I have two main categories of posts with a widget for each one. This results in duplicate arpw-random-post IDs on the page. Could the ID be changed to a class or made configurable?

**Comment by satrya** [comment]
It's possible when the random posts display the same posts with the content (eg index or single post), maybe in the next release I'll just remove the ID or make it more unique.

**Comment by jaden** [comment]
Thanks.

**Comment by satrya** [comment]
Resolve in version 2.0.5 :)
