### ISSUE TITLE
Large numbers of tags will hang wp-admin/wdgets

### ISSUE THREAD

**Issue by jb510** [satrya/advanced-random-posts-widget#4]
The widget form calls an unbounded get_terms( 'post_tag') which returns all tags.  This is fine on some sites, but on sites with thousands of tags this hangs causes very slow queries.  Worse on sites with 10k+ tags wp-admin/widgets.php just won't load.  Less common with categories, but just to be safe should bound those as well.  

We had a similar problem here:
https://github.com/wpsmith/genesis-sandbox-featured-content-widget/issues/7

A couple options:
1) limit the query to something sane get_terms ( 'post_tag', array ( 'number' => 99 ) );

2) Add a filter to the args so devs can control it.

3) 1+2=3! All of the above...  PR coming!

**Comment by satrya** [comment]
I'm sorry for late reply :(, I just have the time to maintenance this project. I'll limit the tag, thank you for your input :)
